version: "3.9"
services: 
  mongo:
      image: mongo:4.4
      command: --nojournal
  orion:
      image: fiware/orion
      depends_on:
        - mongo
        - quantumleap
      ports:
        - "1026:1026"
      command: -dbhost mongo
  # Quantum Leap is persisting Short Term History to Crate-DB
  quantumleap:
    image: smartsdk/quantumleap:0.7.6
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    hostname: quantumleap
    container_name: fiware-quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db

  crate-db:
    image: crate
    hostname: crate-db
    container_name: db-crate
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    volumes:
      - crate-db:/data

  # Other services
  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    depends_on:
      - crate-db
    ports:
      - "3003:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
    crate-db: ~
    grafana: ~